[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "798cfbe305f174b89e82ba317823eac276527865"
os = "macos"

    [[GTK4.download]]
    sha256 = "170f0eff3f579423998a861198cbf28ccd3da997924f2435e12e8abe6bdb1086"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.aarch64-apple-darwin.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "004cae9342379b8902732b12fede01bcc064cec8"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "5df9136b08507a039af2d0162e384a2622f7f05c390c9cbd9eff92d8beac838e"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.aarch64-linux-gnu.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "8dabf4facce3bd581b7a5459e19f1dcb52f98b3c"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "d849543089ef2b06f0220fd81fd7d388a56f8ba26f217470626f4afa19cd4278"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.aarch64-linux-musl.tar.gz"
[[GTK4]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7b90a0e55e0f828ae01533e01a7c1b468d3ae54"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "6539d8bcbd282a2035e6b43cca0f428c265062cc4ad2941ce64d132ad391399c"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.armv6l-linux-gnueabihf.tar.gz"
[[GTK4]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92a89985312435586b143070fdf1365028fb0a2a"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "b8b515678b26196de126472b25dde8c959e73b0dda9ffa32b9d4af0d5ceb47b1"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.armv6l-linux-musleabihf.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2b86170517f7829823e56e0557bc09ab6f3d4c9"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "3d786af58af26626980b3e9cd3b3499580a3f03440638c40bf28ac79d3588dfd"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.armv7l-linux-gnueabihf.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98b09ec37654138a4d3ceb00a8cae0b4ebc198c2"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "53c93677284ea2e19dfb9285da311b05da9206e1b609fd00e577ac51d2de38b2"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.armv7l-linux-musleabihf.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "f21acbea36bf8995886c0ea5e3ffa99490124abc"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "c44c77d24a3e1cbf74b52c9632610e9b2454a9ec3a21e47282ddf82534f7a2eb"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.i686-linux-gnu.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "735fcd86db80bb4c81ecc92ee608be822df681f4"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "149b7af0afaba349dcc81dcfcfd742f431e62f1fbbd96591eb680c6990c9f017"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.i686-linux-musl.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "abca297a1d4a9f4bd9fa76740035a871f3c09fe6"
os = "windows"

    [[GTK4.download]]
    sha256 = "6c2367ad32d3bfdd363cb96e850e57c15cee276d11627d06fe8d39bbc8be9cca"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.i686-w64-mingw32.tar.gz"
[[GTK4]]
arch = "powerpc64le"
git-tree-sha1 = "8adfe19e0bebececf6c68bc00dc60b5b95deacf9"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "b2c9011d0f64f8d4ddbf24ed1cb2098fb8ed94b0236aa8d51e6d1005a91e978f"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.powerpc64le-linux-gnu.tar.gz"
[[GTK4]]
arch = "riscv64"
git-tree-sha1 = "4915604c2d827d9a9b31545ea557afbb5e763800"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "6bbf17ca71c0601fe5bc9f1a5396f0cfec3597f3d2e5a34f8be8d6d3950bf1a8"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.riscv64-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "58d305c4eac72511df37770d7f938ef54fcdfc35"
os = "macos"

    [[GTK4.download]]
    sha256 = "db5c83784e2d49b4fd132256242a74e2c821d23f694f0026f4916b3484509b5b"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.x86_64-apple-darwin.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "8c2e3063590d6141dae76f77a83b0506f0bcba1a"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "7a27235e82612df9cf5f3c5e3f6655021d64c3cf0ff7774462a0f4be5d4ee591"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.x86_64-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "281c333bddd3c77a7c9eccb003d0d43defa082fa"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "14e0c0c8be0c35f5dd9899a0605ecbe62c73a3660602e9684ef0aef0867a9523"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.x86_64-linux-musl.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "5dea0ea51c479c44ac66bcb8260ab3c0fea0fe57"
os = "freebsd"

    [[GTK4.download]]
    sha256 = "81cc813f73e749e22d93ed8949bd10d0b62b5103771613516ae167541c6bffaf"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.x86_64-unknown-freebsd.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "0c90f461eaed84589063697b235156b7a7ea8b87"
os = "windows"

    [[GTK4.download]]
    sha256 = "667be120b4fc1371b499e7943902a91800d94e8b0ba93dfcd869c41eee5d7b5e"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.18.6+0/GTK4.v4.18.6.x86_64-w64-mingw32.tar.gz"
