[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "2c7260b8ecac977bbcd9bbec9fcd340003300088"
os = "macos"

    [[GTK4.download]]
    sha256 = "206626882267fcc8bf17c77f5092a7e6d614c658d1fa5be7869da697234bec0b"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.aarch64-apple-darwin.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "ef2a5ae8aca55ac382f2556313b62014ce0b9942"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "d13cce7bc664c6d518473a085d55e8b1ec11f2d6c42cf8b3adb9afe0733f7382"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.aarch64-linux-gnu.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "31d2e1fc4d7afdae77a1742062431c9001594661"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "439d04617fc61903acab8d475ccfc3457232deded3e66c4c20bcd3939a844bce"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.aarch64-linux-musl.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a187f989ca56e7fb9de86968f48a0fed1b71fd4"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "7b215d08cc2cf617ec13821b6273fa96f787fa68de4621e14892372412e6abfe"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.armv7l-linux-gnueabihf.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1a3ed0292b414f4c024f7fe75d910a305aca4c6"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "99d9d8eda6db90d1ffea0c593240bbc44bc5ab841614e9149f1623917223359d"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.armv7l-linux-musleabihf.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "b2b66bf153482b50d3c5c39abecefc663cb7ebbc"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "6373bedfde7382e73bc69e2447927abdf3b315182c0edc543da0f61d5bd7d18f"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.i686-linux-gnu.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "282d69e8e8bbf32f7346c60346a4fd6a62a5e749"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "cdab7e7dc8ea6df24748c57c68d1f7cbd8a3cec4f76257cda826ffc3c12782e1"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.i686-linux-musl.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "f3c733d7395430579c08b4971896d3fd80281eb9"
os = "windows"

    [[GTK4.download]]
    sha256 = "3ac8d23b45dfdef15b20a3c13815a7ce790436249a693fbc513a4c7acc4c8f94"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.i686-w64-mingw32.tar.gz"
[[GTK4]]
arch = "powerpc64le"
git-tree-sha1 = "43e8d1c17c5c2d1d0f435b95393ca14ee12c59fd"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "87b992ae52251a6a2f97f2217268715d97766617611cd8e02256dfda5f55ad29"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.powerpc64le-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "92a35df43b9a04fcc41c2cc1da2218db3372a250"
os = "macos"

    [[GTK4.download]]
    sha256 = "dae7fdd1d3e3646d9ef3fa85cdfdfeebc6cd9448eae1523ea49defde4bf93ff9"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.x86_64-apple-darwin.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "8975d98222bcd483470cdc118b8bebc638afc390"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "aeb23c13b502713d970621ba182c690011eea7173d5bed293461b86e21007f3d"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.x86_64-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "2f9f7b2c7e2b8f400a6df41d29faca5fec57b583"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "4ba2692e1c387a55c00275d2f43503c8d432287864c8712780ac1ec4ddd77059"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.x86_64-linux-musl.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "1c46da6b019768b3c6d26c626e6c5adebb07f1b8"
os = "freebsd"

    [[GTK4.download]]
    sha256 = "02127215da69e1209c3337a0a041a0ea3075a1f5137dfe5cab525228a2fc1588"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.x86_64-unknown-freebsd.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "e302132ce205461195ddd4d85b49070d593c8828"
os = "windows"

    [[GTK4.download]]
    sha256 = "05e82eca2bb478abd9b46ee6066a5aac38a320a2eb3b3b3b9c00612e832ed6b2"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.8.3+0/GTK4.v4.8.3.x86_64-w64-mingw32.tar.gz"
