[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "f0cda0bdc38557f563f91c4535f51d5cd49f0c70"
os = "macos"

    [[GTK4.download]]
    sha256 = "e75ebd5bff84fe650fdc85ad05a0c88cdae28ec1f68410258942f8e589b5b3fc"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.aarch64-apple-darwin.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "e0186eba978359695cbb32706dcaab9f4dcd1b75"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "5c2c4666ea5688df4a6d5ee2fb2501d251abe9089b3fbf59b1570e4c864f8eac"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.aarch64-linux-gnu.tar.gz"
[[GTK4]]
arch = "aarch64"
git-tree-sha1 = "51612c6db94383a31aaa38f646177c7da58997ed"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "eb66d950d62fe307a9e9a8a06b1bfc5e94bb04d7677fcec3128770a6701badf0"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.aarch64-linux-musl.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f79be2fb3c45286d3eba458dc3e6e4d4bd5ac2e"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "93c81eaa3b12fb177869a2e8228a50ad3ce07c543ffb10e0fff12c899e967753"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.armv7l-linux-gnueabihf.tar.gz"
[[GTK4]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31fa520e266dc7db568c8a648d7103c96e452e50"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "5b9095ddad72dc7fcacd0f3b0ba1de9382a096dc850588451487460d0e370fbb"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.armv7l-linux-musleabihf.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "a4c7ab1dfc1b118df6389f96f01da4b92b6ed7d9"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "fe170d9c03d209a5031649ed62894a036c89f56046816c76bd8cc61f65115fac"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.i686-linux-gnu.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "b16e3a22cd0f2c84c555c4bfc0ee7b9822a93d1f"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "cf5743ebe342d79364bc139bb61f6ff76e01afceb1001df35d48033ae2186cc5"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.i686-linux-musl.tar.gz"
[[GTK4]]
arch = "i686"
git-tree-sha1 = "309a8ebcd6366e75ea2693fd13a94f3a0d84200c"
os = "windows"

    [[GTK4.download]]
    sha256 = "1b60c4f2a2c95275085982b32859caeed94e512d47e4d7290ee4cee905bb2bbd"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.i686-w64-mingw32.tar.gz"
[[GTK4]]
arch = "powerpc64le"
git-tree-sha1 = "2a03129073deec4a478736ee40e70882e2798397"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "7ec04d6af79b0be84170845c5f2cdd4d227e439c9fcef244fd2dcf200ecf094d"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.powerpc64le-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "8f202a8edd428839b1c9fbe5942b3782bac7633b"
os = "macos"

    [[GTK4.download]]
    sha256 = "a4bebbc0cd971b89c1a97bf07f70685a44690740a35c8ad314393db68a825327"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.x86_64-apple-darwin.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "1e1f89bd0bb2253ad7d32bc7e767bb9010f0008c"
libc = "glibc"
os = "linux"

    [[GTK4.download]]
    sha256 = "fba9e6015cf43a9e43c1100aca4ea77224886fa0659a3e6200a955d906b4ae4a"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.x86_64-linux-gnu.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "32a0f934fafc2bca5c861007f0af18bc5f017a9a"
libc = "musl"
os = "linux"

    [[GTK4.download]]
    sha256 = "5f0b1cfb3e158a631871ca06193eedee154a52f54743690d81a76bd096f17aba"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.x86_64-linux-musl.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "97db92f03494416dc79de78c16deccaeed5a8dfc"
os = "freebsd"

    [[GTK4.download]]
    sha256 = "1c3b720949e29d2e56b4d9aab2a28f75546730e7c7e98d463848b016c93b36f2"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.x86_64-unknown-freebsd.tar.gz"
[[GTK4]]
arch = "x86_64"
git-tree-sha1 = "2eadeadea003d33036eda88918a4f46dbe180b0a"
os = "windows"

    [[GTK4.download]]
    sha256 = "d1445dd1057dc378c6bdc864ed62dedb2501dc32ead387af118cb3b16269f100"
    url = "https://github.com/JuliaBinaryWrappers/GTK4_jll.jl/releases/download/GTK4-v4.6.0+1/GTK4.v4.6.0.x86_64-w64-mingw32.tar.gz"
